export const VAULT_FIELD_CONFIGS = {
  insurance: [
    { key: "insurer_name", label: "Insurance Company", type: "text", required: true, placeholder: "e.g. LIC, Star Health, HDFC Life" },
    { key: "policy_type", label: "Policy Type", type: "select", required: true,
      options: ["Life", "Health", "Term", "Motor", "ULIP", "Home", "Travel", "Accident", "Other"] },
    { key: "policy_number", label: "Policy Number", type: "text", required: true },
    { key: "sum_insured", label: "Sum Insured (₹)", type: "number", placeholder: "e.g. 1000000" },
    { key: "premium_amount", label: "Premium Amount (₹)", type: "number", placeholder: "e.g. 25000" },
    { key: "premium_frequency", label: "Premium Frequency", type: "select",
      options: ["Annual", "Semi-Annual", "Quarterly", "Monthly", "Single Premium"] },
    { key: "start_date", label: "Policy Start Date", type: "date" },
    { key: "expiry_date", label: "Expiry / Maturity Date", type: "date" },
    { key: "advisor_name", label: "Advisor Name", type: "text", placeholder: "Who sold this policy? (optional)" },
    { key: "notes", label: "Notes", type: "textarea", placeholder: "Any other details" },
  ],

  investments: [
    { key: "investment_type", label: "Investment Type", type: "select", required: true,
      options: ["Mutual Fund", "Stocks", "PPF", "NPS", "Bonds", "ETF", "ELSS", "Other"] },
    { key: "fund_name", label: "Fund / Company Name", type: "text", required: true, placeholder: "e.g. SBI Bluechip Fund, Infosys" },
    { key: "folio_number", label: "Folio / Account Number", type: "text", placeholder: "e.g. 1234567890" },
    { key: "amount_invested", label: "Amount Invested (₹)", type: "number" },
    { key: "current_value", label: "Current Value (₹)", type: "number" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "advisor_name", label: "Advisor Name", type: "text", placeholder: "Who manages this? (optional)" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],

  bank_accounts: [
    { key: "bank_name", label: "Bank Name", type: "text", required: true, placeholder: "e.g. SBI, HDFC, ICICI" },
    { key: "account_type", label: "Account Type", type: "select", required: true,
      options: ["Savings", "Current", "Salary", "NRI — NRE", "NRI — NRO"] },
    { key: "account_number_last4", label: "Account Number (last 4 digits only)", type: "text",
      placeholder: "XXXX", maxLength: 4, hint: "Store only the last 4 digits for safety" },
    { key: "ifsc_code", label: "IFSC Code", type: "text", placeholder: "e.g. SBIN0001234" },
    { key: "branch", label: "Branch", type: "text", placeholder: "e.g. Hyderabad Main Branch" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],

  fixed_deposits: [
    { key: "bank_name", label: "Bank / Institution", type: "text", required: true, placeholder: "e.g. SBI, Post Office, HDFC" },
    { key: "fd_number", label: "FD Number / Reference", type: "text" },
    { key: "principal_amount", label: "Principal Amount (₹)", type: "number", required: true },
    { key: "interest_rate", label: "Interest Rate (%)", type: "number", placeholder: "e.g. 6.5" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "maturity_date", label: "Maturity Date", type: "date" },
    { key: "maturity_amount", label: "Maturity Amount (₹)", type: "number" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],

  loans: [
    { key: "loan_type", label: "Loan Type", type: "select", required: true,
      options: ["Home Loan", "Car Loan", "Personal Loan", "Education Loan", "Business Loan", "Gold Loan", "Other"] },
    { key: "lender_name", label: "Lender / Bank", type: "text", required: true, placeholder: "e.g. HDFC Bank, SBI" },
    { key: "loan_account_number", label: "Loan Account Number", type: "text" },
    { key: "outstanding_amount", label: "Outstanding Amount (₹)", type: "number" },
    { key: "emi_amount", label: "EMI Amount (₹)", type: "number" },
    { key: "emi_date", label: "EMI Debit Date (day of month)", type: "number", placeholder: "e.g. 5" },
    { key: "start_date", label: "Loan Start Date", type: "date" },
    { key: "end_date", label: "Loan End Date", type: "date" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],

  real_estate: [
    { key: "property_type", label: "Property Type", type: "select", required: true,
      options: ["Flat / Apartment", "Independent House", "Plot / Land", "Commercial", "Farm Land", "Other"] },
    { key: "address", label: "Property Address", type: "textarea", required: true, placeholder: "Full address of the property" },
    { key: "area", label: "Area", type: "text", placeholder: "e.g. 1200 sq.ft" },
    { key: "purchase_price", label: "Purchase Price (₹)", type: "number" },
    { key: "current_value", label: "Current Market Value (₹)", type: "number" },
    { key: "purchase_date", label: "Purchase Date", type: "date" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],

  gold: [
    { key: "gold_type", label: "Gold Type", type: "select", required: true,
      options: ["Physical Gold (Coins / Bars)", "Jewellery", "Digital Gold", "Sovereign Gold Bond (SGB)", "Gold ETF", "Other"] },
    { key: "description", label: "Description", type: "text", required: true, placeholder: "e.g. 24K Coin, Necklace, SGB 2021-22 Series" },
    { key: "weight_grams", label: "Weight (grams)", type: "number", placeholder: "e.g. 10" },
    { key: "purchase_price", label: "Purchase Price (₹)", type: "number" },
    { key: "current_value", label: "Current Value (₹)", type: "number" },
    { key: "purchase_date", label: "Purchase Date", type: "date" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],

  documents: [
    { key: "document_type", label: "Document Type", type: "select", required: true,
      options: ["PAN Card", "Aadhaar Card", "Passport", "Voter ID", "Driving Licence", "Birth Certificate", "Marriage Certificate", "Degree Certificate", "Other"] },
    { key: "name_on_doc", label: "Name on Document", type: "text", required: true },
    { key: "document_number", label: "Document Number (masked)", type: "text",
      placeholder: "e.g. ABCDE1234F or XXXX-XXXX-1234",
      hint: "Do not store full Aadhaar — use masked form only" },
    { key: "issue_date", label: "Issue Date", type: "date" },
    { key: "expiry_date", label: "Expiry Date", type: "date" },
    { key: "notes", label: "Notes", type: "textarea" },
  ],

  nominees: [
    { key: "name", label: "Full Name", type: "text", required: true },
    { key: "relation", label: "Relation", type: "select", required: true,
      options: ["Spouse", "Son", "Daughter", "Father", "Mother", "Brother", "Sister", "Other"] },
    { key: "mobile", label: "Mobile Number", type: "text", placeholder: "10-digit mobile" },
    { key: "dob", label: "Date of Birth", type: "date" },
    { key: "email", label: "Email", type: "text", placeholder: "email@example.com" },
    { key: "aadhaar_last4", label: "Aadhaar (last 4 digits only)", type: "text",
      placeholder: "XXXX", maxLength: 4, hint: "Store only last 4 digits for safety" },
    { key: "address", label: "Address", type: "textarea" },
  ],
};
