import type { Metadata } from "next";
import Navbar from "@/yvity-landing/app/components/Navbar";
import Footer from "@/yvity-landing/app/components/Footer";

export const metadata: Metadata = {
  title: "Terms & Conditions — YVITY",
  description: "Read the terms and conditions governing your use of the YVITY platform — India's credibility platform for insurance advisors.",
};

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-[#F8F6F1] font-poppins">
      <Navbar />

      <main className="mx-auto w-full max-w-[860px] px-4 pb-20 pt-28 sm:px-6 sm:pt-32 lg:px-8 lg:pt-36">

        {/* Header */}
        <div className="mb-12 text-center">
          <p className="mb-3 text-xs font-semibold uppercase tracking-[0.18em] text-[#F59E0B]">Legal</p>
          <h1 className="font-cormorant text-4xl font-bold leading-tight text-[#0A4A4A] sm:text-5xl">Terms &amp; Conditions</h1>
          <p className="mt-4 text-sm text-[#6B7280]">Last updated: June 2025 &nbsp;·&nbsp; Effective date: June 2025</p>
        </div>

        <div className="rounded-3xl border border-[#E4E2DB] bg-white px-7 py-10 shadow-sm sm:px-10 sm:py-12">

          <section className="mb-8">
            <p className="text-sm leading-relaxed text-[#374151]">
              Welcome to YVITY. These Terms and Conditions ("Terms") govern your access to and use of the YVITY platform, website (<strong>yvity.com</strong>), and all associated services (collectively, the "Platform"). By registering, accessing, or using the Platform, you ("User", "you", "Advisor") agree to be bound by these Terms. If you do not agree, you must discontinue use immediately.
            </p>
            <p className="mt-3 text-sm leading-relaxed text-[#374151]">
              YVITY is operated by a company registered in India. All services are provided for use within India.
            </p>
          </section>

          <HR />

          <H2>1. Definitions</H2>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li><strong>"Platform"</strong> means the YVITY website, mobile-optimised web app, and all associated API services.</Li>
            <Li><strong>"Advisor"</strong> means an IRDAI-registered insurance advisor who creates a profile on YVITY.</Li>
            <Li><strong>"Client" / "Visitor"</strong> means any individual who visits an Advisor's public profile on YVITY.</Li>
            <Li><strong>"YVITY Score"</strong> means the credibility metric computed by the Platform based on profile completeness, verification status, activity, and peer recommendations.</Li>
            <Li><strong>"Membership Plan"</strong> means a paid subscription (Silver or Gold) that unlocks additional Platform features.</Li>
            <Li><strong>"Content"</strong> means any information, text, images, documents, or materials uploaded or generated by you on the Platform.</Li>
          </ul>

          <HR />

          <H2>2. Eligibility</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            To use YVITY as an Advisor, you must:
          </p>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li>Be at least 18 years of age.</Li>
            <Li>Be a licensed insurance advisor registered with the Insurance Regulatory and Development Authority of India (IRDAI), or be an employee / agent of an IRDAI-registered entity.</Li>
            <Li>Provide accurate and truthful information during registration and profile setup.</Li>
            <Li>Have the legal authority to enter into this agreement.</Li>
          </ul>
          <p className="mt-3 text-sm leading-relaxed text-[#374151]">
            YVITY reserves the right to verify your credentials and reject or revoke access if eligibility requirements are not met.
          </p>

          <HR />

          <H2>3. Account Registration and Security</H2>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li>You must register using a valid Indian mobile number and/or email address. Authentication is via OTP only — YVITY does not store passwords.</Li>
            <Li>You are responsible for maintaining the confidentiality of OTP codes. Do not share OTPs with anyone — YVITY staff will never ask for your OTP.</Li>
            <Li>You must notify us immediately at <a href="mailto:support@yvity.com" className="font-semibold text-[#0A4A4A]">support@yvity.com</a> if you suspect unauthorised access to your account.</Li>
            <Li>One account per individual. Creating duplicate accounts is prohibited and may result in immediate suspension.</Li>
          </ul>

          <HR />

          <H2>4. Advisor Profile and Content</H2>

          <H3>4.1 Accuracy of Information</H3>
          <p className="text-sm leading-relaxed text-[#374151]">
            You warrant that all information you provide — including your name, credentials, IRDAI licence number, years of experience, qualifications, services, and testimonials — is accurate, complete, and not misleading. Providing false information is a serious violation and may result in immediate account termination and reporting to IRDAI.
          </p>

          <H3>4.2 Profile Verification</H3>
          <p className="text-sm leading-relaxed text-[#374151]">
            YVITY manually reviews profiles and verification documents before approving a public profile. Approval is at YVITY's sole discretion. An unapproved profile is not visible to the public. YVITY may request additional documentation at any time.
          </p>

          <H3>4.3 Content Ownership and License</H3>
          <p className="text-sm leading-relaxed text-[#374151]">
            You retain ownership of Content you upload. By uploading Content, you grant YVITY a non-exclusive, royalty-free, worldwide licence to display, reproduce, and distribute that Content solely for the purpose of operating and promoting the Platform (e.g., featuring your profile in search results or marketing materials).
          </p>
          <p className="mt-3 text-sm leading-relaxed text-[#374151]">
            You may withdraw this licence at any time by removing the relevant Content or deleting your account.
          </p>

          <H3>4.4 Prohibited Content</H3>
          <p className="text-sm leading-relaxed text-[#374151]">
            You must not upload or share Content that:
          </p>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li>Is false, misleading, or fraudulent.</Li>
            <Li>Infringes on intellectual property rights of any third party.</Li>
            <Li>Contains defamatory, discriminatory, or obscene material.</Li>
            <Li>Violates IRDAI advertising or solicitation guidelines.</Li>
            <Li>Includes unsolicited promotional material or spam.</Li>
            <Li>Promotes competing platforms or services deceptively.</Li>
          </ul>

          <HR />

          <H2>5. YVITY Score</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            The YVITY Score is a proprietary credibility metric computed by the Platform. It reflects factors including:
          </p>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li>Profile completeness (photo, bio, services, career details).</Li>
            <Li>Profile verification and IRDAI certificate upload.</Li>
            <Li>Number and quality of verified peer recommendations.</Li>
            <Li>Platform engagement and login activity.</Li>
            <Li>Membership plan tier.</Li>
          </ul>
          <p className="mt-3 text-sm leading-relaxed text-[#374151]">
            The Score is indicative only and does not constitute a financial assessment, endorsement, or guarantee of an Advisor's competence. YVITY reserves the right to modify the Score methodology at any time.
          </p>

          <HR />

          <H2>6. Membership Plans</H2>

          <H3>6.1 Plan Tiers</H3>
          <p className="text-sm leading-relaxed text-[#374151]">
            YVITY offers free and paid membership tiers. Paid plans (Silver, Gold) unlock additional features such as higher content limits, intro video upload, advanced profile customisation, and priority visibility. Plan features are subject to change with reasonable notice.
          </p>

          <H3>6.2 Payment</H3>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li>All payments are processed in Indian Rupees (INR) via Razorpay, a PCI-DSS compliant payment gateway.</Li>
            <Li>By completing a payment, you authorise YVITY to charge the applicable membership fee.</Li>
            <Li>Prices are inclusive of applicable GST unless stated otherwise.</Li>
            <Li>Invoices are delivered to your registered email and WhatsApp after successful payment.</Li>
          </ul>

          <H3>6.3 Refund Policy</H3>
          <p className="text-sm leading-relaxed text-[#374151]">
            Membership fees are non-refundable except in the following circumstances:
          </p>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li>Technical failure: If a payment is debited but the plan is not activated due to a verified technical error on YVITY's side, a full refund will be issued within 7 business days.</Li>
            <Li>Account rejection: If YVITY rejects your profile during verification after payment (e.g., ineligibility), a pro-rata refund for unused days may be provided at YVITY's discretion.</Li>
          </ul>
          <p className="mt-3 text-sm leading-relaxed text-[#374151]">
            Refund requests must be made within 7 days of the payment date to <a href="mailto:support@yvity.com" className="font-semibold text-[#0A4A4A]">support@yvity.com</a>.
          </p>

          <H3>6.4 Subscription Renewal and Expiry</H3>
          <p className="text-sm leading-relaxed text-[#374151]">
            Membership plans are not auto-renewed. You will receive a reminder notification before your plan expires. On expiry, your account reverts to the free tier; your profile and data are retained but paid features are disabled.
          </p>

          <HR />

          <H2>7. IRDAI Compliance</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            YVITY is a profile and credibility platform — it is not a licensed insurance broker, distributor, or aggregator. YVITY does not solicit, sell, or distribute insurance products on behalf of any Advisor or insurer.
          </p>
          <p className="mt-3 text-sm leading-relaxed text-[#374151]">
            Advisors are solely responsible for ensuring their conduct on and through the Platform complies with IRDAI regulations, including guidelines on advertising, client solicitation, and disclosure requirements. YVITY is not liable for any IRDAI regulatory action arising from an Advisor's conduct.
          </p>

          <HR />

          <H2>8. Prohibited Conduct</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            You must not:
          </p>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li>Attempt to reverse-engineer, scrape, or extract data from the Platform.</Li>
            <Li>Use bots, crawlers, or automation to access or interact with the Platform.</Li>
            <Li>Impersonate another advisor, person, or entity.</Li>
            <Li>Submit fake testimonials, reviews, or peer recommendations.</Li>
            <Li>Attempt to manipulate your YVITY Score through inauthentic activity.</Li>
            <Li>Engage in any activity that disrupts or degrades Platform performance.</Li>
            <Li>Use the Platform for any purpose prohibited by Indian law.</Li>
          </ul>

          <HR />

          <H2>9. Intellectual Property</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            All Platform software, design, trademarks, logos, and proprietary content (excluding User Content) are the intellectual property of YVITY and are protected under applicable Indian IP law. You may not copy, reproduce, distribute, or create derivative works from Platform IP without explicit written permission.
          </p>
          <p className="mt-3 text-sm leading-relaxed text-[#374151]">
            "YVITY", the YVITY logo, and "Credibility that Connects" are trademarks of YVITY. Unauthorised use is prohibited.
          </p>

          <HR />

          <H2>10. Disclaimers and Limitation of Liability</H2>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li><strong>No endorsement:</strong> YVITY does not endorse, recommend, or guarantee any Advisor listed on the Platform. Clients should independently verify an Advisor's credentials before transacting.</Li>
            <Li><strong>No financial advice:</strong> Nothing on YVITY constitutes financial, insurance, or investment advice.</Li>
            <Li><strong>Service availability:</strong> YVITY is provided "as is". We aim for high availability but do not guarantee uninterrupted access.</Li>
            <Li><strong>Limitation of liability:</strong> To the maximum extent permitted by Indian law, YVITY's total liability for any claim arising from use of the Platform is limited to the amount paid by you in the 12 months preceding the claim. YVITY is not liable for indirect, incidental, or consequential damages.</Li>
          </ul>

          <HR />

          <H2>11. Indemnification</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            You agree to indemnify and hold harmless YVITY, its officers, employees, and affiliates from any claims, losses, liabilities, damages, and expenses (including legal fees) arising from: (a) your use of the Platform; (b) your Content; (c) your violation of these Terms; or (d) your violation of applicable law including IRDAI regulations.
          </p>

          <HR />

          <H2>12. Suspension and Termination</H2>
          <ul className="mt-2 flex flex-col gap-2 text-sm text-[#374151]">
            <Li>YVITY may suspend or terminate your account at any time for violation of these Terms, provision of false information, or conduct that harms the Platform or its users.</Li>
            <Li>You may delete your account at any time through Platform settings or by requesting deletion at <a href="mailto:support@yvity.com" className="font-semibold text-[#0A4A4A]">support@yvity.com</a>.</Li>
            <Li>On termination, your public profile is immediately unpublished. Personal data is deleted per our Privacy Policy retention schedule.</Li>
            <Li>Paid membership fees are non-refundable on termination for Terms violation.</Li>
          </ul>

          <HR />

          <H2>13. Modifications to the Platform and Terms</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            YVITY may modify features, pricing, or these Terms at any time. For material changes, we will provide at least 14 days' notice via email or Platform notification. Continued use after the notice period constitutes acceptance. If you disagree with changes, you may delete your account before the effective date.
          </p>

          <HR />

          <H2>14. Governing Law and Dispute Resolution</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            These Terms are governed by the laws of India. Any dispute arising from these Terms shall be subject to the exclusive jurisdiction of courts in India. YVITY encourages resolution of disputes first through our support team at <a href="mailto:support@yvity.com" className="font-semibold text-[#0A4A4A]">support@yvity.com</a> before initiating formal proceedings.
          </p>

          <HR />

          <H2>15. Grievance Redressal</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            In compliance with the IT Act, 2000 and DPDP Act, 2023, our Grievance Officer can be contacted at:
          </p>
          <div className="mt-3 rounded-xl bg-[#F8F6F1] p-4 text-sm text-[#374151]">
            <p className="font-semibold text-[#0A4A4A]">Grievance Officer — YVITY</p>
            <p className="mt-1">Email: <a href="mailto:support@yvity.com" className="font-semibold text-[#0A4A4A] underline-offset-2 hover:underline">support@yvity.com</a></p>
            <p className="mt-1 text-xs text-[#6B7280]">We acknowledge complaints within 48 hours and resolve them within 30 days.</p>
          </div>

          <HR />

          <H2>16. Entire Agreement</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            These Terms, together with our Privacy Policy, constitute the entire agreement between you and YVITY with respect to the Platform and supersede all prior agreements, representations, or understandings. If any provision is found unenforceable, the remaining provisions remain in full effect.
          </p>

          <HR />

          <H2>17. Contact</H2>
          <p className="text-sm leading-relaxed text-[#374151]">
            For questions about these Terms, contact us:
          </p>
          <div className="mt-3 rounded-xl bg-[#F8F6F1] p-4 text-sm text-[#374151]">
            <p className="font-semibold text-[#0A4A4A]">YVITY Support</p>
            <p className="mt-1">Email: <a href="mailto:support@yvity.com" className="font-semibold text-[#0A4A4A] underline-offset-2 hover:underline">support@yvity.com</a></p>
            <p>Web: <a href="https://yvity.com/contact" className="font-semibold text-[#0A4A4A] underline-offset-2 hover:underline">yvity.com/contact</a></p>
          </div>

        </div>
      </main>

      <Footer />
    </div>
  );
}

function HR() {
  return <hr className="my-8 border-[#E4E2DB]" />;
}

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="mb-4 font-cormorant text-2xl font-bold text-[#0A4A4A]">{children}</h2>;
}

function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="mb-3 mt-5 font-poppins text-sm font-semibold text-[#0A4A4A]">{children}</h3>;
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-2">
      <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#F59E0B]" />
      <span>{children}</span>
    </li>
  );
}
